# Generated by Django 4.2 on 2023-05-12 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_homepage', models.PositiveSmallIntegerField(choices=[('0', 'Yes'), ('1', 'No / Not Yet')], default=None)),
                ('category_type', models.PositiveSmallIntegerField(choices=[('3', 'Music'), ('4', 'Commercial')], default=None)),
                ('client_name', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('project_order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('project_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('content_url_number', models.PositiveSmallIntegerField()),
                ('content_description', models.CharField(max_length=300)),
                ('content_orientation', models.PositiveSmallIntegerField(choices=[('6', 'Portrait'), ('7', 'Landscape')], default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.project')),
            ],
        ),
    ]
