# Generated by Django 4.2 on 2023-04-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_assets_delete_project_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.CharField(max_length=255)),
                ('content_description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='api.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Project_Assets',
        ),
    ]
