# Generated by Django 4.2 on 2023-04-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_asset_delete_project_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.project'),
        ),
    ]
