# Generated by Django 4.2 on 2023-04-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_asset_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_asset',
            name='content_1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_1_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_2_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_3_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_4_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_4_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_5_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_5_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_6_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_6_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_7_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_7_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_8_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_8_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_9_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='content_9_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
