# Generated by Django 4.2 on 2023-04-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_asset_content_1_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_title',
        ),
    ]
