# Generated by Django 4.2 on 2023-04-17 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_title_project_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_asset',
            name='content_1_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_1_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_2_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_2_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_3_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_3_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_4_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_4_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_5_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_5_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_6_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_6_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_7_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_7_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_8_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_8_url',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_9_description',
        ),
        migrations.RemoveField(
            model_name='project_asset',
            name='content_9_url',
        ),
        migrations.AlterField(
            model_name='project_asset',
            name='content_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project_asset',
            name='content_url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
