# Generated by Django 4.2 on 2023-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_asset_content_url_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_asset',
            name='content_url_number',
            field=models.PositiveIntegerField(),
        ),
    ]
