# Generated by Django 4.2 on 2023-04-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230419_2223'),
        ('api', '0009_alter_project_asset_content_url_number'),
    ]

    operations = [
    ]
