# Generated by Django 4.2 on 2023-04-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20230419_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project_asset',
            name='asset_order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
