# Generated by Django 4.2 on 2023-05-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_project_asset_content_orientation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project_asset',
            options={},
        ),
    ]
