# Generated by Django 4.2 on 2023-05-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_project_options_alter_project_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['on_homepage', 'category_type', 'client_name', 'project_title', 'project_order', 'project_type', 'description']},
        ),
        migrations.AlterModelOptions(
            name='project_asset',
            options={'ordering': ['project', 'content_url', 'content_url_number', 'content_description', 'content_orientation', 'asset_order']},
        ),
    ]
