# Generated by Django 4.2 on 2023-05-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_project_options_alter_project_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project_asset',
            options={},
        ),
    ]
