# Generated by Django 4.2 on 2023-05-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_options_alter_project_asset_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_asset',
            name='asset_order',
        ),
    ]
