# Generated by Django 4.2 on 2023-04-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('music', 'Music'), ('commercial', 'Commercial')], max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_url', models.CharField(max_length=255)),
                ('content_description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jwt_auth.project')),
            ],
        ),
    ]
