# Generated by Django 4.2 on 2023-04-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_project_project_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_photo',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Project_Photo',
        ),
    ]
